In [ ]:
%load_ext autoreload
%autoreload 2
%precision %.4f
import numpy as np
np.set_printoptions(precision=4, suppress=1)
import utils_postprocess_HPC as postp

In [ ]:
f = open('../run/_runstrings_ML.txt','r')
runstrings = f.readlines()
f.close()

import mne; print(  mne.__version__ )
from IPython import get_ipython; ipython = get_ipython()

In [ ]:
from jupyter_helpers.notifications import Notifications
p = '/usr/share/sounds/gnome/default/alerts/'
sound_file = '../beep-06.mp3'
#p1 = p + 'glass.ogg'; p2 = p + 'sonar.ogg';
p1 = sound_file; p2 = p1
Notifications(success_audio=p1, time_threshold=2,
    failure_audio=p2)  #    ,integration='GNOME')

In [ ]:
#istr = 61
istr = 0
istr = 9
istr = 2
mstr0 = '%run -i ../run/' + runstrings[istr][:-1] 
#mstr0 += ' --exit_after LDA_best_LFP'
#mstr0 += ' --exit_after XGB_main' 
#mstr0 += ' --exit_after corr_matrix' 
mstr0 += ' --exit_after load' 
#mstr0 += ' --skip_LDA 1' 
mstr0 += ' --n_jobs 1' 
#mstr0 += '--load_XGB_params_auto 0 --load_EBM_params_auto 1' 
#mstr0 += ' --XGB_tune_param 0 --EBM_tune_param 0 --subskip_fit 8 --n_jobs 1' 
print(mstr0)

In [ ]:
#%debug
ipython.magic(mstr0)

In [ ]:
featnames

In [ ]:
exCB, data_modalities, prefix

In [ ]:
brain_side_to_use

In [ ]:
use_featfname_old_regex

In [ ]:
feat_info

In [ ]:
            '{}_feats_NMS{}_{}_{}chs_nfeats{}_skip{}_wsz{}_grp{}-{}{}.npz'.\
            format(rawn,feat_body_side, sources_type,'[0-9]+', '[0-9]+', skip, windowsz,
                    src_file_grouping_ind, src_grouping, crp_str)


In [ ]:
best_LFP_info_file

In [ ]:
best_LFP_info[subj].keys()

In [ ]:
# to try later
#%run -i ../run/run_ML.py -r S01_off_hold,S01_off_move,S01_on_hold,S01_on_move --prefix modLFP_onlyH_brainleft_disjoint --mods LFP --feat_types H_act,H_mob,H_compl --subskip_fit 8 --brain_side_to_use left --LFP_side_to_use left --param_file ML_searchLFP_both_HPC.ini --groupings_to_use merge_nothing --int_types_to_use basic --runCID 16499349608940  --n_jobs 1

In [ ]:
features_to_use

In [ ]:
set([]) | set([1,2,3])

In [ ]:
print(class_ids_grouped)
class_to_check,class_ind_to_check, class_ind_to_check_lenc

In [ ]:
# Q: if I change manuall classes order, will it just change the number or something else as well?

In [ ]:
set(class_labels_for_heavy), set(class_labels_nm_for_heavy)

In [ ]:
lab_enc = preprocessing.LabelEncoder()
lab_enc_nm = preprocessing.LabelEncoder()

lab_enc.   fit(class_labels_for_heavy)
lab_enc_nm.fit(class_labels_nm_for_heavy)
#lab_enc.classes_ = lab_enc.classes_[::-1]
#lab_enc_nm.classes_ = lab_enc_nm.classes_[::-1]

In [ ]:
lab_enc.classes_, lab_enc_nm.classes_

In [ ]:
class_ind_to_check

In [ ]:
lab_enc.transform([class_ind_to_check])[0], lab_enc_nm.transform([class_ind_to_check])[0]
#lab_enc.transform([class_ind_to_check])[0], lab_enc_nm.transform([class_ind_to_check])[0]


In [ ]:
class_ind_to_check_lenc_nm, class_ind_to_check_lenc

In [ ]:
set(class_labels_nm)

In [ ]:
set(class_labels)

In [ ]:
S01_on_hold_feats_NMSboth_parcel_aal_543chs_nfeats198_skip32_wsz256_grp10-0.npz


In [ ]:
regex

In [ ]:
inp_sub

In [ ]:
fscm = featsel_per_method['interpret_EBM']['all']

In [ ]:
fscm.keys()

In [ ]:
fscm['perf_dict'].keys()

In [ ]:
fscm['scores_from_loc'][0]

In [ ]:
fscm['perf_per_cp']

In [ ]:
s = '%run -i ../run/run_ML.py -r S01_off_hold,S03_off_hold --param_file ML_joint_one_LFP_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic --mods msrc --feat_types H_act --parcel_group_names Sensorimotor --prefix onlyH_act_SM_noLFP'
s = s + ' --save_output 0 --XGB_tune_param 0 --XGB_tune_param 0 --EBM_CV 1 --subskip_fit 4 --skip_LDA 1'
ipython.magic(s)

In [ ]:
ebm.additive_terms_[1].shape

In [ ]:
ebm.term_standard_deviations_[0].shape

In [ ]:
len(ebm.additive_terms_)

In [ ]:
ebm.feature_groups_

In [ ]:
ebm.intercept_

In [ ]:
len( ebm.feature_names['feature_names'] )

In [ ]:
ebm_creopts

In [ ]:
class_weights_cur.shape

In [ ]:
X.shape

In [ ]:
from utils import runFilePart

In [ ]:
runFilePart('../run/run_ML.py','', 2603)

In [ ]:
load_XGB_params_auto

In [ ]:
s = ('%run -i ../run/run_ML.py -r S01_off_hold,S01_on_hold --feat_types H_act '
'--parcel_group_names !Sensorimotor  --prefix test --EBM_CV 1 --save_output 0')
ipython.magic(s)

In [ ]:
feature_names_pri[0]

In [ ]:
s=('%run -i ../run/run_ML.py -r S01_off_hold,S01_on_hold,S01_off_move,S01_on_move,S02_off_hold,S02_on_hold,S02_off_move,S02_on_move,S03_off_hold,S03_off_move,S04_off_hold,S04_on_hold,S04_off_move,S04_on_move,S05_off_hold,S05_on_hold,S05_off_move,S05_on_move,S07_off_hold,S07_on_hold,S07_off_move,S07_on_move '
'--param_file ML_joint2_ICA_one_LFP_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic '
'--feat_types H_act --prefix onlyH_act --exit_after corr_matrix --use_ICA_for_classif 0 --compute_ICA 0')
ipython.magic(s + ' --show_plots 0')

In [ ]:
use_main_LFP_chan

In [ ]:
featnames_nice

In [ ]:
s=('%run -i ../run/run_ML.py -r S01_on_hold,S01_on_move,S02_on_hold --param_file ML_joint_one_LFP_HPC.ini ' 
'--groupings_to_use merge_movements --int_types_to_use trem_vs_hold&move --feat_types H_act,H_mob,H_compl --prefix onlyH '
'--use_ICA_for_classif 1 --output_subdir test_ICA --compute_ICA 1 --calc_VIF 0 '
'--XGB_tune_param 0 --subskip_fit 4 --parcel_group_names !Sensorimotor --XGB_featsel_feats all ')
ipython.magic(s + ' --show_plots 0')

In [ ]:
groups = {'1_': np.array(featnames_for_fit)[np.arange(10)], '2_':np.array(featnames_for_fit)[np.arange(10,17)]  } 

#%debug
expl = utsne.shapr_proxy(X_for_heavy,class_labels_good_for_classif,featnames_for_fit,
                 groups=groups,n_samples = len(class_labels_for_heavy) // 4, n_batches = 1,
                 class_weights=class_weights, add_clf_creopts=add_clf_creopts, n_combinations = None)

In [ ]:
expl[0][2]

In [ ]:
X_for_heavy.shape

In [ ]:
roi_labels

# Shapr

In [ ]:
xgbobj.__dict__.keys()

In [ ]:
add_clf_creopts

In [ ]:
xgbobj.booster

In [ ]:
f = np.load(fname_ML_full_intermed,allow_pickle=True)

#f['results_cur'][()]['XGB_analysis_versions']['all_present_features']['perf_dict'].keys()
f['XGBojb']

In [ ]:
fname_ML_full_intermed = pjoin( gv.data_dir, output_subdir, filename_to_save)


#     for rn,a in outputs_grouped.items():
#         _, mult_clf_output = a

results_cur['filename_full'] = fname_ML_full_intermed
outputs_grouped = {'': (None,results_cur) }
postp.loadFullScores(outputs_grouped, force_reload=1)

#results_cur['XGB_analysis_versions']['all_present_features']['perf_dict']['perfs_CV'][0]

body_side = 'L'
if chnames_LFP is None:
    chnames_LFP = getChnamesFromFeatlist(featnames_sub, mod='LFP')
separate_by_band = False
separate_by_band2 = False
merge_Hjorth = 1
Hjorth_diff_color = True
grand_average_per_feat_type = False
cross_source_groups = False

cmap = plt.cm.get_cmap('tab20', 20)


clrs,feature_groups_names,feat_groups_all  = \
    postp.prepareFeatGroups(featnames,body_side,
                      roi_labels['all_raw'],cmap,
                      chnames_LFP, separate_by_band,
                      separate_by_band2,
                      merge_Hjorth,
                      Hjorth_diff_color,
                      grand_average_per_feat_type,
                      cross_source_groups)


groups = {}
inds_list = []
for cgri,cgr in enumerate(feat_groups_all):
    # indices of features
    inds = utsne.selFeatsRegexInds(featnames,cgr)
    if len(inds_list):
        assert 0 == len( set(inds) & set(inds_list[-1])  )
    inds_list += [ inds ]
    
    if len(inds):
        #groups[feature_groups_names[cgri]] = inds
        groups[feature_groups_names[cgri]] = featnames[inds]
    
#     if feature_names_subset is not None:
#         inds_small_set = selFeatsRegexInds(feature_names_subset,cgr)
#         inds = [ feature_names_l.index(feature_names_subset[i]) for i in inds_small_set  ]
#     else:
#         inds = utsne.selFeatsRegexInds(feature_names,cgr)

#groups = {'1_': np.array(featnames_for_fit)[np.arange(10)], '2_':np.array(featnames_for_fit)[np.arange(10,17)]  } 

n_samples = min( len(class_labels_for_heavy), max(1000, len(class_labels_for_heavy) // 4) )


n_samples = 100
n_combinations = 100
n_batches = 1  # more would reduce data usage but slow

xgbobj = results_cur['XGBobj']
add_clf_creopts2 =  {'tree_method'         :    xgbobj.tree_method,
'n_jobs'              :    xgbobj.n_jobs,
'min_child_weight'    : xgbobj.min_child_weight,
'max_depth'           : xgbobj.max_depth,
'eta'                 : xgbobj.kwargs['eta'],
'subsample'          :   xgbobj.subsample }

In [ ]:
groups

In [ ]:
#%debug
expl = utsne.shapr_proxy(X_for_heavy,class_labels_good_for_classif,featnames,
                 groups=groups,n_samples = n_samples, n_batches = n_batches,
                 class_weights=class_weights, add_clf_creopts=add_clf_creopts2, 
                         n_combinations = n_combinations)

In [ ]:
add_clf_creopts2

In [ ]:
len(class_labels_for_heavy)

In [ ]:
len(groups),groups

In [ ]:
feature_groups_names

In [ ]:
num_class

In [ ]:
import pandas as pd
import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri
from rpy2.robjects.packages import importr
import rpy2.robjects as ro
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri

numpy2ri.activate()
#import feather as ft

X_train = X_for_heavy
y_train = class_labels_good_for_classif

assert X_train.ndim == 2
assert X_train.shape[0] == len(y_train)

colnames = map(str,range(X_train.shape[1]))
df = pd.DataFrame(X_train, columns = colnames  )

xgboost = importr('xgboost')

with localconverter(ro.default_converter + pandas2ri.converter):
    r_from_pd_df = ro.conversion.py2rpy(df)

X_train_r = robjects.r['matrix'](X_train, ncol=X_train.shape[1])
dtrain = xgboost.xgb_DMatrix(X_train_r, label = y_train)
#robjects.r('colnames(X_train_r) <- range(10)' )

# num_class = len(set(y_train) )
# model = xgboost.xgboost(dtrain, nround = 20,
# verbose = False, weight=class_weights,
#                        objective = "multi:softprob" , num_class=num_class,
#                         **add_clf_creopts)#, **add_fitopts)


num_class = len(set(y_train) )
model = xgboost.xgboost(dtrain, nround = 20,
verbose = False, weight=class_weights,
                       objective = "binary:logistic" , num_class=num_class,
                        **add_clf_creopts)#, **add_fitopts)


In [ ]:
help(xgboost.train)

In [ ]:
add_clf_creopts

In [ ]:
X_for_heavy.shape

In [ ]:
help(xgboost.train)

In [ ]:
import xgboost
dtrain = xgboost.DMatrix(X_for_heavy,class_labels_good_for_classif)
xgboost.train({'objective': "binary:logistic" }, dtrain=dtrain,
    num_boost_round = 20)#, **add_fitopts) 

In [ ]:
from utils_tSNE import shapr_proxy

In [ ]:
%load shapr_proxy

In [ ]:
expl.__dict__

In [ ]:
r_df = expl[0]

from rpy2.robjects import pandas2ri
import rpy2.robjects as ro
from rpy2.robjects.conversion import localconverter
with localconverter(ro.default_converter + pandas2ri.converter):
  pd_from_r_df = ro.conversion.rpy2py(r_df)

pd_from_r_df

In [ ]:
XGB_featsel_feats

In [ ]:
featur

In [ ]:
len(feature_names_pri[0])

In [ ]:
                    !OccipitalMid
                    !TemporalMid
                    !FrontalSup
                    !FrontalMed
                    !Sensorimotor


In [ ]:
XGB_tune_param

In [ ]:
pca_derived_featinds

In [ ]:
Xconcat_good_cur.shape

In [ ]:
Xconcat_imputed.shape

In [ ]:
# %run -i ../run/run_ML.py -r S01_on_hold,S01_on_move,S02_on_hold --param_file ML_joint_one_LFP_HPC.ini \
# --groupings_to_use merge_nothing --int_types_to_use trem_vs_quiet --fbands --prefix allb_tremor --exit_after load

In [ ]:
#%debug
#ipython.magic(mstr0 + ' --exit_after load --show_plots 0')
ipython.magic(mstr0 + ' --show_plots 0')

#savefile_raw

In [ ]:
savefile_rawname_format

In [ ]:
            filename_to_save =  utils.genMLresFn(rawnames,sources_type, src_file_grouping_ind, src_grouping,
                    prefix, n_channels, 999,
                    899, skip, windowsz, use_main_LFP_chan, grouping_key,int_types_key,
                                        rawname_format = savefile_rawname_format,
                                        custom_rawname_str=custom_rawname_str)


In [ ]:
rawnames

In [ ]:
X_for_heavy.shape, class_labels_for_heavy.shape,group_labels.shape

In [ ]:
group_labels_dict.keys()

In [ ]:
group_labels_dict['medcond'].shape

In [ ]:
from sklearn.model_selection import KFold,GroupKFold
kf = GroupKFold(n_splits=2)  # no shuffling is possible here
split_res = kf.split(X_for_heavy,class_labels_for_heavy,groups=group_labels_dict['medcond'] )


#l1,l2 =  list(split_res)[1]

for l1,l2 in split_res:
    print( len(l1),len(l2), groups[l1] , groups[l2])

In [ ]:
kf = GroupKFold(n_splits=3)  # no shuffling is possible here
lbls = np.array( [0,0,0,0,1,1,2,1,1,2,2,2,2] )
split_res = kf.split(np.arange(13),[0,0,0,0,1,1,2,1,1,2,2,2,2],groups=lbls )


#l1,l2 =  list(split_res)[1]

for l1,l2 in split_res:
    print( len(l1),len(l2), lbls[l1] , lbls[l2])

In [ ]:
from sklearn.model_selection import LeaveOneGroupOut
LeaveOneGroupOut( )

In [ ]:
groups

In [ ]:
groups = group_labels_dict['medcond']
logo = LeaveOneGroupOut()
logo.get_n_splits(groups=groups)  # 'groups' is always required
print(logo)
for train_index, test_index in logo.split(X_for_heavy,class_labels_for_heavy,groups=group_labels_dict['medcond']):
    print(groups[train_index] )

In [ ]:
group_labels[l1]

In [ ]:
group_labels

In [ ]:
filename_to_save

In [ ]:
savefile_rawname_format='subj,medcond_glob'

In [ ]:
custom_rawname_str

In [ ]:
filename_to_save =  utils.genMLresFn(rawnames,sources_type, src_file_grouping_ind, src_grouping,
        prefix, n_channels, Xconcat_imputed.shape[1],
        pcapts.shape[1], skip, windowsz, use_main_LFP_chan, grouping_key,int_types_key,
                             rawname_format = savefile_rawname_format,
                                     custom_rawname_str=custom_rawname_str)
filename_to_save

In [ ]:
np.arange(3,10,2)

In [ ]:
X_cur.shape

In [ ]:
mstr00 = '%run -i ../run/run_ML.py -r {} --param_file ML_joint_one_LFP_HPC.ini ' +\
    '--groupings_to_use merge_movements --int_types_to_use trem_vs_hold&move --mods LFP --prefix modLFP ' +\
    '--subskip_fit 4 --skip_LDA 1 --custom_rawname_str 1,2,3mixed_test'
mstr00 = mstr00.format('S01_off_hold,S01_off_move,S02_off_move,S04_off_hold')
print(mstr00)

In [ ]:
ipython.magic(mstr00)

In [ ]:
featsel_methods

In [ ]:
custom_rawname_str

In [ ]:
results_cur['featsel_per_method'].keys()

In [ ]:
featsel_info.keys()

In [ ]:
X_cur.shape

In [ ]:
Xconcat_good_cur.shape

In [ ]:
len(class_weights), X_cur.shape

In [ ]:
add_clf_creopts

In [ ]:
                            r0_across = utsne.getPredPowersCV(clf_XGB,X_cur,y_cur,
                                class_ind_to_check_lenc, printLog = 0,
                                n_splits=len( set(group_labels) ), add_fitopts=add_fitopts,
                                add_clf_creopts=add_clf_creopts,
                                ret_clf_obj=False, seed=0, label_groups=group_labels[::subskip_fit])
                            rc['across'][label_group_name] = r0_across

                            perfstr = utsne.sprintfPerfs(r0_across['perf_aver'])
                            print(f'{label_group_name} label grouping gave perf {perfstr}')
                            print( r0_across['confmat_aver'] * 100 )


In [ ]:
                class_labels, class_labels_good, revdict, class_ids_grouped,inds_not_neut  = \
                    utsne.makeClassLabels(sides_hand, grouping,
                        int_types_to_distinguish,
                        ivalis_tb_indarrays_merged, bininds_noartif_nounlab,
                        len(Xconcat_imputed),
                        rem_neut = discard_remaining_int_types_during_fit)


In [ ]:
len(class_labels), len(inds_not_neut), len(class_labels_good), len(bininds_noartif_nounlab), Xsubset_to_fit.shape

In [ ]:
                    add_clf_creopts_CV = dict(add_clf_creopts.items())
                    if len(numpoints_per_class_id)  > 2:
                        add_clf_creopts_CV['objective'] = 'multi:softprob'
                        add_clf_creopts_CV['num_class'] = len(numpoints_per_class_id)
                        tune_metric = 'mlogloss'
                    else:
                        add_clf_creopts_CV['objective'] = 'binary:logistic'
                        tune_metric = 'logloss'

                    #search_grid['eta'] = np.array([.3, .2, .1, .05, .01, .005])
                    XGB_param_list_search_seq = [ ['max_depth','min_child_weight'],
                                            ['subsample', 'eta'] ]

                    print('Start XGB param tuning, XGB_param_list_search_seq=',XGB_param_list_search_seq)
                    add_clf_creopts_orig = add_clf_creopts
                    add_clf_creopts, best_params_list, cv_resutls_best_list,\
                        num_boost_round_best=\
                        utsne.gridSearchSeq(X_cur,y_cur, add_clf_creopts_CV,
                                        XGB_params_search_grid,
                                        XGB_param_list_search_seq,
                                        num_boost_round=100,
                            early_stopping_rounds=10, nfold=n_splits, seed=0,
                                           sel_num_boost_round=1,
                                            main_metric=tune_metric, printLog=1)


In [ ]:
set(class_labels_good_for_classif), len(class_labels_good_for_classif)

In [ ]:
set(class_labels_good)

In [ ]:
numpoints_per_class_id

In [ ]:
X_cur.shape

In [ ]:
y_cur.shape

In [ ]:
discard_remaining_int_types_during_fit

In [ ]:
                            r0_across = utsne.getPredPowersCV(clf_XGB,X_cur,y_cur,
                                class_ind_to_check_lenc, printLog = 0,
                                n_splits=n_splits, add_fitopts=add_fitopts,
                                add_clf_creopts=add_clf_creopts,
                                ret_clf_obj=False, seed=0, label_groups=group_labels[::subskip_fit])


In [ ]:
len(class_labels_good), len(class_labels_good)/4, len(class_labels)

In [ ]:
len(bininds_concat_good), len(group_labels), len(group_labels)/subskip_fit

In [ ]:
len(inds_not_neut), len(inds_not_neut2)

In [ ]:
                for itkc,glv in group_labels_dict.items():
                    group_labels_dict[itkc] = glv[inds_not_neut]


In [ ]:
len(group_labels_dict['subj'])

In [ ]:
X_cur.shape

In [ ]:
y_cur.shape

In [ ]:
fsh

In [ ]:
featsel_methods_all_possible

In [ ]:
add_clf_creopts

In [ ]:
set(class_labels_good)

In [ ]:
# sys.setrecursionlimit(10000)

# import utils_postprocess as pp
# ld = dict( locals().items() )
# for llab,lv in ld.items():
#     print(llab)
#     pp.printSizeInfo(lv)

In [ ]:
sys.setrecursionlimit(10000)

In [ ]:
sys.getrecursionlimit()

In [ ]:
numpoints_per_class_id

In [ ]:
results_cur['best_LFP']['LDA']

In [ ]:
s_almost_all = 'S01_off_hold,S01_off_move,S02_off_hold,S02_off_move,S04_off_hold,S04_off_move,S05_off_hold,S05_off_move,S07_off_hold,S07_off_move'
s_all_off = s_almost_all + ',S03_off_hold,S03_off_move'
s_all_on = s_almost_all.replace('_off_','_on_')

In [ ]:
mstr0 = '%run -i ../run/run_ML.py -r ' + \
    'S01_off_hold,S01_off_move,S02_off_hold,S02_off_move,S04_off_hold,S04_off_move,S05_off_hold,S05_off_move,S07_off_hold,S07_off_move ' + \
    '--param_file ML_nofeatsel_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic --self_couplings_only 1 --mods msrc --prefix modSrc_self --exit_after XGB_main --allow_CUDA 0'
mstr0 += ' --show_plots 0'

In [ ]:
mstr0 = '%run -i ../run/run_ML.py -r ' + \
    'S01_off_hold,S01_off_move,S02_off_hold,S02_off_move,S04_off_hold,S04_off_move,S05_off_hold,S05_off_move,S07_off_hold,S07_off_move ' + \
    '--param_file ML_nofeatsel_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic --mods msrc --prefix modSrc_self --exit_after XGB_main --allow_CUDA 0'
mstr0 += ' --show_plots 0'

In [ ]:
mstr0 = '%run -i ../run/run_ML.py -r ' + \
    'S01_off_hold,S01_off_move,S02_off_hold,S02_off_move,S04_off_hold,S04_off_move,S05_off_hold,S05_off_move,S07_off_hold,S07_off_move,S03_off_hold,S03_off_move ' + \
    '--param_file ML_nofeatsel_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic --mods msrc --prefix modSrc_self --exit_after XGB_main --allow_CUDA 0'
mstr0 += ' --show_plots 0'
kind = 'off_with_S03'

In [ ]:
mstr0 = '%run -i ../run/run_ML.py -r ' + \
    'S01_off_hold,S01_off_move,S02_off_hold,S02_off_move,S04_off_hold,S04_off_move,S05_off_hold,S05_off_move,S07_off_hold,S07_off_move ' + \
    '--param_file ML_nofeatsel_HPC.ini --groupings_to_use merge_movements --int_types_to_use basic --mods msrc --prefix modSrc_self --exit_after XGB_main --allow_CUDA 0'
mstr0 += ' --show_plots 0'
mstr0 = mstr0.replace('_off_','_on_')

In [ ]:
mstr0, kind

In [ ]:
import gc
print(kind)
#depths = [3,4,5,6]
depths = [3, 6, 8, 10]
#depths = [4]
resutls_per_depth = {}
for cur_depth in depths:    
    gc.collect()
    mstr1 = mstr0 + f' --XGB_max_depth {cur_depth}'
    
    ipython.magic(mstr1)
    resutls_per_depth[cur_depth] = results_cur
    
for cd in resutls_per_depth:
    results_cur = resutls_per_depth[cd]
    r0 = results_cur['XGB_analysis_versions']['all_present_features']['perf_dict']
    perfstr = utsne.sprintfPerfs(r0['perf_aver'])
    print(f'{cd}:   XGB {XGB_version_name} perfs are {perfstr}')
    print( r0['confmat_aver'] * 100 )

  

In [ ]:
#import 
featis = np.random.randint( len(featnames),size=20)
postp.plotFeatHists(rawnames,featnames,featis,X_pri,Xconcat, bindict_per_rawn,
                  ivalis_tb_indarrays_merged, xlim_common = (-6,6))

In [ ]:
# modSrc off med (no S03)
# 3:   XGB all_present_features perfs are 78.55%,81.73%,61.37%
# [[78.5524 10.1157 11.3318]
#  [20.4269 54.5132 25.0599]
#  [16.3914 17.6036 66.005 ]]
# 6:   XGB all_present_features perfs are 88.61%,95.14%,84.71%
# [[88.6131  5.4496  5.9373]
#  [ 5.7199 80.2536 14.0265]
#  [ 4.1124  9.4194 86.4682]]
# 8:   XGB all_present_features perfs are 91.42%,98.47%,92.39%
# [[91.4243  4.0299  4.5458]
#  [ 1.7566 90.3171  7.9263]
#  [ 1.33    4.9196 93.7504]]
# 10:   XGB all_present_features perfs are 92.52%,99.06%,94.15%
# [[92.5208  3.253   4.2262]
#  [ 1.0206 93.505   5.4743]
#  [ 0.8791  2.9675 96.1535]]

# modSrc off med (with S03)
# 3:   XGB all_present_features perfs are 79.39%,82.02%,58.46%
# [[79.3911 10.3852 10.2238]
#  [19.7135 53.4299 26.8566]
#  [16.4489 20.9141 62.637 ]]
# 6:   XGB all_present_features perfs are 87.03%,95.05%,81.95%
# [[87.0329  6.8438  6.1232]
#  [ 5.4368 78.5579 16.0053]
#  [ 4.5176 12.5858 82.8966]]
# 8:   XGB all_present_features perfs are 88.81%,98.57%,90.56%
# [[88.8083  5.6869  5.5047]
#  [ 1.5933 89.2997  9.1069]
#  [ 1.2827  6.4514 92.266 ]]
# 10:   XGB all_present_features perfs are 89.52%,99.19%,92.43%
# [[89.518   5.1263  5.3557]
#  [ 0.8968 93.1867  5.9165]
#  [ 0.7401  3.6538 95.6062]]

# modSrc on med
# 3: XGB all_present_features perfs are 77.87%,85.01%,60.41%
# [[77.8652  9.0964 13.0384]
#  [14.2411 62.7034 23.0555]
#  [15.5233 21.3497 63.127 ]]

In [ ]:
# if I use all off (besides S03)
# mem usage (GB) =  154.61236953735352

In [ ]:
gc.collect()

In [ ]:
    #import 
featis = np.random.randint( len(featnames),size=20)
postp.plotFeatHists(rawnames,featnames,featis,X_pri,Xconcat, bindict_per_rawn,
                  ivalis_tb_indarrays_merged, xlim_common = (-6,6))

In [ ]:
for cur_depth in depths:    
    resutls_per_depth[cur_depth] 
    
    perfstr = utsne.sprintfPerfs(r0['perf_aver'])
    print(f'XGB {XGB_version_name} perfs are {perfstr}')
    print( r0['confmat_aver'] * 100 )

In [ ]:
feature_names_all

In [ ]:
35.80%,88.57%,30.57%

In [ ]:
help(clf_XGB.fit)

In [ ]:
add_clf_creopts['max_depth'] = 6;
print(add_clf_creopts)

clf_XGB = XGBClassifier(**add_clf_creopts)
clf_XGB.fit(X_cur, y_cur, **add_fitopts,
            sample_weight=class_weights)
r0 = utsne.getPredPowersCV(clf_XGB,X_cur,y_cur,
    class_ind_to_check_lenc, printLog = 0,
    n_splits=n_splits, add_fitopts=add_fitopts,
    add_clf_creopts=add_clf_creopts,
    ret_clf_obj=False, seed=0)

perfstr = utsne.sprintfPerfs(r0['perf_aver'])
print(f'XGB {XGB_version_name} perfs are {perfstr}')
print( r0['confmat_aver'] * 100 )



In [ ]:
clf_XGB.cv(booster_params,num_boost_round,nfold,metrics=['merror'],shuffle=True,seed=0)

In [ ]:
#https://rdrr.io/cran/xgboost/man/xgb.cv.html
# error binary classification error rate
# rmse Rooted mean square error
# logloss negative log-likelihood function
# mae Mean absolute error
# mape Mean absolute percentage error
# auc Area under curve
# aucpr Area under PR curve
# merror Exact matching error, used to evaluate multi-class classification

# feaval   customized evaluation function. 
# Returns list(metric='metric-name', value='metric-value') with given prediction and dtrain.

In [ ]:
import xgboost

In [ ]:
help(xgboost.cv)

In [ ]:
clf_XGB

In [ ]:
add_clf_creopts['max_depth'] = 1;
print(add_clf_creopts)

clf_XGB = XGBClassifier(**add_clf_creopts)
clf_XGB.fit(X_cur, y_cur, **add_fitopts,
            sample_weight=class_weights)
r0 = utsne.getPredPowersCV(clf_XGB,X_cur,y_cur,
    class_ind_to_check_lenc, printLog = 0,
    n_splits=n_splits, add_fitopts=add_fitopts,
    add_clf_creopts=add_clf_creopts,
    ret_clf_obj=False, seed=0)

perfstr = utsne.sprintfPerfs(r0['perf_aver'])
print(f'XGB {XGB_version_name} perfs are {perfstr}')
print( r0['confmat_aver'] * 100 )



In [ ]:
r0['perfs_CV'][0][-1],r0['perfs_CV'][1][-1]

In [ ]:
feat_inds_curLFP, feat_inds_except_curLFP = getFeatIndsRelToOnlyOneLFPchan(featnames,
        chn=chn_LFP, chnames_LFP=chnames_LFP)
len(featnames), len(feat_inds_curLFP), len(feat_inds_except_curLFP)

In [ ]:
np.array(featnames)[feat_inds_except_curLFP], chn_LFP

In [ ]:
np.array(featnames)[feat_inds_curLFP], chn_LFP

In [ ]:
XGB_max_depth

In [ ]:
r0.keys()

In [ ]:
help(getFeatIndsRelToOnlyOneLFPchan)

In [ ]:
from xgboost import XGBClassifier
clf_XGB = XGBClassifier()


In [ ]:
isinstance(clf_XGB,XGBClassifier)

In [ ]:
preds = res_all_feats['CV_aver']['ldaobj'].predict(Xconcat_good_cur)

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
counts, list(sorted(set(class_labels_good) ))

In [ ]:
class_ids_grouped

In [ ]:
class_labels_good_mrg = class_labels_good.copy()
class_labels_good_mrg[class_labels_good_mrg == 3] = 2
preds_mrg = preds.copy()
preds_mrg[preds_mrg==3] = 2

In [ ]:
lbls = list(sorted(set(class_labels_good_mrg) )); print(lbls)
for lbl in lbls:
    TP = np.sum((preds_mrg==lbl) & (class_labels_good_mrg == lbl))
    P = np.sum(class_labels_good_mrg==lbl)
    pred_P = np.sum(preds_mrg==lbl)
    print(f'lbl={lbl}, P={P}, pred_P={pred_P}, TP={TP}')
nav = recall_score(class_labels_good_mrg, preds_mrg, average=None,   labels=lbls)
#bav = recall_score(class_labels_good_mrg, preds_mrg, average='binary',   labels=lbls)
miv = recall_score(class_labels_good_mrg, preds_mrg, average='micro',labels=lbls)
mav = recall_score(class_labels_good_mrg, preds_mrg, average='macro',labels=lbls)
wav = recall_score(class_labels_good_mrg, preds_mrg, average='weighted',labels=lbls)
print(nav)
print(miv,mav,wav)

In [ ]:
lbls = list(sorted(set(class_labels_good) ))
for lbl in lbls:
    TP = np.sum((preds==lbl) & (class_labels_good == lbl))
    P = np.sum(class_labels_good==lbl)
    pred_P = np.sum(preds==lbl)
    print(f'lbl={lbl}, P={P}, pred_P={pred_P}, TP={TP}')
nav = recall_score(class_labels_good, preds, average=None,   labels=lbls)
#Calculate metrics globally by counting the total true positives, false negatives and false positives.
miv = recall_score(class_labels_good, preds, average='micro',labels=lbls)
# Calculate metrics for each label, and find their unweighted mean
mav = recall_score(class_labels_good, preds, average='macro',labels=lbls)
# weighted Calculate metrics for each label, and find their average weighted by support 
#(the number of true instances for each label). This alters ‘macro’ to account for label imbalance;
wav = recall_score(class_labels_good_mrg, preds_mrg, average='weighted',labels=lbls)
print(nav)
print(miv,mav,wav)

# weighted means that we give more importance to predicting most abundant label 
# -- which I don't want (unless it is tremor), I want to have equal importance

In [ ]:
#In a multi-class classification setup, micro-average is preferable 
#if you suspect there might be class imbalance 
#(i.e you may have many more examples of one class than of other classes).

In [ ]:
# computes only for selected labels, but includes also points with other labels
recall_score(class_labels_good, preds, average=None,labels=[1,3]) 

In [ ]:
utsne.getClfPredPower(res_all_feats['CV_aver']['ldaobj'],Xconcat_good_cur,class_labels_good,1)

In [ ]:
utsne.getClfPredPower(res_all_feats_mrg['CV_aver']['ldaobj'],Xconcat_good_cur,class_labels_good,1)

In [ ]:
import copy
revdict_mrg = {}
revdict_mrg[1] = revdict[1]
revdict_mrg[2] = 'notrem_L&hold_L&move_L'

res_all_feats_mrg = utsne.calcLDAVersions(Xconcat_good_cur, Xconcat_imputed, class_labels_good_mrg,
                      n_components_LDA-1, class_ind_to_check, revdict_mrg,
                            calcName=lda_version_name,n_splits=n_splits)


In [ ]:
from sklearn.utils.class_weight import compute_sample_weight
class_weights = compute_sample_weight('balanced',class_labels_good)
print(np.unique(ws))

In [ ]:
# need to be finished
def reconstructImportanceUsingVIF(importances_subset, colinds_good_VFsel, colinds_bad_VFsel, 
                                  VFsel_featsets_list,VFsel_linreg_objs):
    assert importances_subset.ndim == 3
    importances_full = np.ones( (len(VFsel_featsets_list[0]),importances_subset.shape[dim] ) ) * np.nan
    importances_full[colinds_good_VFsel] = importances_subset
    for badind,featis,linreg_obj in list(zip(colinds_bad_VFsel,VFsel_featsets_list,VFsel_linreg_objs))[::-1]:
        
        importances_full[badind] = importances_full[featis] * linreg_obj.coef_  + linreg_obj.intercept

## Histograms

In [ ]:
%matplotlib inline

In [ ]:
bindict_per_rawn.keys()

In [ ]:
bindict_per_rawn[rawnames[0]]['beh_state']

In [ ]:
gp.int_types_basic

In [ ]:
X_pri[rawi].shape

In [ ]:
len(featnames)

In [ ]:
#prefix

In [ ]:
np.random.randint(180,size=10)

In [ ]:
ivalis_tb_indarrays_merged.keys()

In [ ]:
help(ax.set_ylim)

In [ ]:
rawnames

In [ ]:
scale_feat_combine_type

In [ ]:
import utils_postprocess_HPC as postp

#import 
featis = np.random.randint(180,size=20)

postp.plotFeatHists(rawnames,featnames,featis,X_pri,Xconcat, bindict_per_rawn,
                  ivalis_tb_indarrays_merged, xlim_common = (-5,5))



In [ ]:
pjoin(gv.dir_fig, figname)

In [ ]:
help(plt.hist)

In [ ]:
recall_score(class_labels_good, preds, average='samples')

In [ ]:
res_all_feats['CV_aver'].keys()

In [ ]:
# sklearn.metrics.recall_score(y_true, y_pred, *, labels=None, 
#                              pos_label=1, average='binary', sample_weight=None, zero_division='warn')[source]¶

In [ ]:
results_cur['best_LFP'].keys()

In [ ]:
best_inds_XGB

In [ ]:
indlist

In [ ]:
C_subset.shape

In [ ]:
istr = 18
mstr0 = '%run -i ../run/' + runstrings[istr][:-1] + ' --allow_CUDA 0' 
mstr0.replace('load_TFR 0', 'load_TFR 1')
mstr0.replace('load_CSD 0', 'load_CSD 1')
mstr0.replace('load_TFRCSD_max_age_h 240', 'load_TFRCSD_max_age_h 400')

addopts = ' --exit_after prescale_data'

mstr0 = mstr0 + addopts
#+ ' --load_TFR 1 --load_CSD 1 --allow_CUDA 0'
print(mstr0)

In [ ]:
istr = 1
mstr0 = '%run -i ../run/' + runstrings[istr][:-1] + ' --allow_CUDA 0' 
addopts = ' --n_jobs 21'
mstr0 = mstr0 + addopts
#+ ' --load_TFR 1 --load_CSD 1 --allow_CUDA 0'
print(mstr0)

In [ ]:
from IPython import get_ipython; ipython = get_ipython()
#%debug
ipython.magic(mstr0)

In [ ]:
utils.ann2ivalDict(anndict_per_intcat['artif']['MEG'])

In [ ]:
for side in ['L','R']:
    chis_msrc = mne.pick_channels_regexp(subfeature_order,f'msrc{side}.*')
    temp_ann = utils.getArtifForFiltering(f'msrc{side}', anndict_per_intcat['artif']['MEG'] )
    print(f'bandFilter: for {len(chis_msrc)} chis current anns are ',
          temp_ann,temp_ann.onset,temp_ann.duration,temp_ann.description)
    #print(len(chis_msrc) )


In [ ]:
if bands_only == 'fine':
    fband_names = gv.fband_names_fine
else:
    fband_names = gv.fband_names_crude

if bands_only == 'fine':
    fband_names_inc_HFO = gv.fband_names_fine_inc_HFO
else:
    fband_names_inc_HFO = gv.fband_names_crude_inc_HFO
    fband_names_HFO = fband_names_inc_HFO[len(fband_names):]  # that HFO names go after


In [ ]:
    if bands_only == 'fine':
        fband_names = gv.fband_names_fine
    else:
        fband_names = gv.fband_names_crude

    print('Filtering and Hilbert')

    sfreqs = [sfreq, sfreq_hires]
    skips = [skip, skip_hires]
    dat_pri_persfreq = [dat_pri, dat_lfp_hires_pri]


    # note that we can have different channel names for different raws
    #raw_perband_flt_pri_persfreq = []
    #raw_perband_bp_pri_persfreq = []

    smoothen_bandpow = 0

    # band filter computed separately for different datasets
    raw_perband_flt_pri, raw_perband_bp_pri, chnames_perband_flt_pri, chnames_perband_bp_pri  = \
        ugf.bandFilter(rawnames, times_pri, main_sides_pri, side_switched_pri,
              sfreqs, skips, dat_pri_persfreq, fband_names_inc_HFO, gv.fband_names_HFO_all,
              fbands, n_jobs_flt, allow_CUDA, subfeature_order, subfeature_order_lfp_hires,
              smoothen_bandpow, ann_MEGartif_prefix_to_use, 
                       anndict_per_intcat_per_rawn= anndict_per_intcat_per_rawn)


In [ ]:
mstr

In [ ]:
import importlib as il; il.reload(ugf)

In [ ]:
import gc; gc.collect()

In [ ]:
    raw_perband_flt_pri, raw_perband_bp_pri, chnames_perband_flt_pri, chnames_perband_bp_pri  = \
        ugf.bandFilter(rawnames, times_pri, main_sides_pri, side_switched_pri,
              sfreqs, skips, dat_pri_persfreq, fband_names_inc_HFO, gv.fband_names_HFO_all,
              fbands, n_jobs_flt, allow_CUDA, subfeature_order, subfeature_order_lfp_hires,
              smoothen_bandpow, ann_MEGartif_prefix_to_use, anndict_per_intcat_per_rawn= anndict_per_intcat_per_rawn)


In [ ]:
mstr = 
print(mstr)

In [ ]:
from IPython import get_ipython; ipython = get_ipython()

mstr='%run -i ../run/'+runstrings[18]
mstr = mstr.replace('-- ','')
mstr = mstr[:-1] + ' --load_TFR 1 --load_CSD 1 --allow_CUDA 0'
display(mstr)

In [ ]:
ipython.magic(mstr)

In [ ]:
if recalc_stats_multi_band:
    #means_perband_flt_pri_,_ = \
    indsets, means_perband_flt_pri_, stds_perband_flt_pri_, stats_per_indset_per_band_flt =  \
    ugf.gatherMultiBandStats(rawnames,raw_perband_flt_pri, times_pri,
                            chnames_perband_flt_pri, side_switched_pri, sfreq,
                            baseline_int, scale_data_combine_type,
                            feat_stats_artif_handling,
                            require_intervals_present = [baseline_int],
                             bindict_per_rawn=bindict_per_rawn)
    #means_perband_bp_pri_,_ = \
    indsets, means_perband_bp_pri_, stds_perband_bp_pri_, stats_per_indset_per_band_bp =  \
    ugf.gatherMultiBandStats(rawnames,raw_perband_bp_pri, times_pri,
                            chnames_perband_bp_pri, side_switched_pri, sfreq,
                            baseline_int, scale_data_combine_type,
                            feat_stats_artif_handling,
                            require_intervals_present = [baseline_int],
                             bindict_per_rawn=bindict_per_rawn)

    #stats_multiband_flt = stats_per_indset_per_band_flt
    #stats_multiband_bp  = stats_per_indset_per_band_bp

    #stats_multiband_flt = means_perband_flt_pri_
    #stats_multiband_bp  = means_perband_bp_pri_


    curstatinfo = {'indsets':indsets, 'rawnames':rawnames,
                   'stats_per_indset':stats_per_indset_per_band_flt }
    curstatinfo['means' ]  = means_perband_flt_pri_
    curstatinfo['stds' ]   = stds_perband_flt_pri_
    stats_multiband_flt = curstatinfo

    curstatinfo = {'indsets':indsets, 'rawnames':rawnames,
                   'stats_per_indset':stats_per_indset_per_band_bp }
    curstatinfo['means' ]  = means_perband_bp_pri_
    curstatinfo['stds' ]   = stds_perband_bp_pri_
    stats_multiband_bp = curstatinfo
else:
    assert not prescale_data, 'If we prescale data, loaded multi band stats is not valid!'
    prefix = stats_fn_prefix
    # first arg should be None so that I can specify explicitly the prefix
    # it is necessary because I run this scripts not with the same set of
    # rawnames compared to what was used for stats gathering
    fname_stats_multi_band = utils.genStatsMultiBandFn(None, new_main_side, data_modalities,
                                    use_main_LFP_chan, src_file_grouping_ind,
                                    src_grouping, bands_only, prefix )

    fname_stats_full = pjoin( gv.data_dir, input_subdir, fname_stats_multi_band)
    f = np.load(fname_stats_full, allow_pickle=True)
    rawnames_stats =  f['rawnames']
    assert set(rawnames).issubset(rawnames_stats)
    #means_perband_flt_pri_ =  f['stats_multiband_flt_per_ct'][()][scale_data_combine_type]['means']
    #means_perband_bp_pri_  =  f['stats_multiband_bp_per_ct'][()][scale_data_combine_type]['means']

    stats_multiband_flt =  f['stats_multiband_flt_per_ct'][()][scale_data_combine_type]
    stats_multiband_bp  =  f['stats_multiband_bp_per_ct'][()][scale_data_combine_type]

    indsets = stats_multiband_bp['indsets']
    #stats_per_indset_per_band_flt

################# extract stats for the given baseline int

rawi_mask,allinds = upre.getIndsetMask(indsets, allow_repeating=False, allow_holes = False)

means_perband_flt_pri = len(rawnames) * [dict()]
means_perband_bp_pri = len(rawnames) * [dict()]

statdicts =[stats_multiband_flt, stats_multiband_bp ]
mdicts =[means_perband_flt_pri, means_perband_bp_pri ]
for mdi,md in enumerate(mdicts):
    for rawind in range(len(rawnames)):
        indseti = rawi_mask[rawind]
        for bandname in statdicts[mdi]['means']:
            a = statdicts[mdi]['means'][bandname][indseti][baseline_int]
            #print(a)
            mdicts[mdi][rawind][bandname] = a

if 'rbcorr' in features_to_use:  #raw band corr
    if bands_only == 'fine':
        bandPairs = [('tremor','tremor', 'corr'),
                    ('low_beta','low_beta', 'corr'), ('high_beta','high_beta', 'corr'),
                    ('low_gamma','low_gamma', 'corr') , ('high_gamma','high_gamma', 'corr') ]
    else:
        bandPairs = [('tremor','tremor', 'corr'), ('beta','beta', 'corr'), ('gamma','gamma', 'corr') ]

    rbcorrs_pri     = [0] * len(rawnames)
    wbd_rbcorr_pri  = [0] * len(rawnames)
    rbcor_names_pri = [0] * len(rawnames)
    for rawind in range(len(dat_pri)):
        fn = pre_rbcorr_fname.format(rawnames[rawind], n_channels_pri[rawind] )
        fn = pjoin(gv.data_dir, output_subdir, fn)
        if load_rbcorr and os.path.exists(fn):
            print('Load rbcorr from {}'.format(fn) )
            f = np.load(fn, allow_pickle=True)
            bpcorrs      =f['rbcorrs'    ]
            bpcor_names  =f['rbcor_names']
            wbd_bpcorr   =f['wbd_rbcorr' ]
        else:
            print('Starting rbcorr for datset {}'.format(rawind) )
            raw_perband =  raw_perband_flt_pri[rawind]
            chnames_per_band =  chnames_perband_flt_pri[rawind]
            if rbcorr_use_local_means:
                means_perband = None
                assert not rbcorr_use_zero_mean
            else:
                means_perband = means_perband_flt_pri[rawind]

            if rbcorr_use_zero_mean:
                assert not rbcorr_use_local_means
                means_perband = 0.

            rbcorrs = []
            rbcor_names = []
            for bp in bandPairs:
                print('band pair ',bp)
                rbcorrs_curbp,rbcor_names_curbp,dct_nums, wbd_rbcorr = \
                computeCorr(raw_perband, chnames_per_band=chnames_per_band,
                                        defnames=chnames_tfr,
                                        parcel_couplings=parcel_couplings,
                                        LFP2parcel_couplings=LFP2parcel_couplings,
                                        LFP2LFP_couplings=LFP2LFP_couplings,
                                        res_group_id=newchn_grouping_ind,
                                        skip=skip, windowsz = windowsz,
                                        band_pairs = [bp], n_jobs=n_jobs,
                                        positive=0, templ='{}_.*',
                                        roi_labels=roi_labels,
                                        sort_keys=srcgrouping_names_sorted,
                                        means=means_perband,
                                        local_means=rbcorr_use_local_means)
                assert len(rbcor_names_curbp) > 0
                gc.collect()
                rbcorrs     += rbcorrs_curbp
                rbcor_names += rbcor_names_curbp

            rbcorrs = np.vstack(rbcorrs)

            for feati in range(len(rbcor_names) ):
                rbcor_names[feati] = 'rb' + rbcor_names[feati]

            if save_rbcorr:
                print('Saving rbcorr ',fn)
                #fn = pjoin(gv.data_dir, output_subdir,'{}_rbcorr.npz'.format(rawnames[rawind] ) )
                np.savez( fn , rbcorrs=rbcorrs, rbcor_names=rbcor_names, wbd_rbcorr=wbd_rbcorr)
                gc.collect()

        rbcor_names_pri[rawind] = rbcor_names
        rbcorrs_pri    [rawind] = rbcorrs
        wbd_rbcorr_pri [rawind] = wbd_rbcorr
    if do_cleanup:
        del  raw_perband_flt_pri
        del  rbcorrs
    gc.collect()


else:
    rbcorrs_pri = None
    rbcor_names = None
    wbd_rbcorr_pri = None


In [ ]:
side_switched_pri

In [ ]:
 utils.ann2ivalDict( tuple(anndict_per_intcat_per_rawn.items())[0] [1]['beh_state'] )

In [ ]:
features_to_use

In [ ]:
%load_ext autoreload
%autoreload 2
%precision %.4f
import numpy as np
np.set_printoptions(precision=4, suppress=1)

#%debug
%run -i ../run/run_ML.py -r S01_off_hold,S01_off_move \
--bands_type crude --sources_type parcel_aal \
--src_grouping 0 --src_grouping_fn 10 --rescale_feats 1 \
--skip_XGB 0\
--fbands_mod1 msrc:gamma --fbands_mod2 LFP:beta\
--subskip_fit 16 \
--allow_CUDA 0\
--n_splits 2 \
--calc_MI 0 \
--heavy_fit_red_featset 1\
--groupings_to_use merge_nothing \
--int_types_to_use basic\
--save_output 0 --prefix test \
--show_plots 0 \
--featsel_method XGB_Shapley \
--n_jobs 1 \
--load_only 1
#--prep_for_clf_only 1
#--featsel_method SHAP_XGB,interpret_EBM,XGB_Shapley  
#--featsel_methods XGB_Shapley
#,interpret_EBM 

In [ ]:
X_allfeats.shape

In [ ]:
Xconcat.shape

In [ ]:
help(pd.DataFrame)

In [ ]:
import seaborn as sns
import pandas as pd
df = pd.DataFrame(Xconcat, columns=good_feats)

In [ ]:
good_feats[:3]

In [ ]:
df.head()

In [ ]:
df[good_feats[:3]]

In [ ]:
sns_plot = sns.pairplot(df[good_feats[:5]])
fig_fname = pjoin(gv.dir_fig, f'{rn_str}_pairplot.png' )
print(fig_fname)
sns_plot.savefig(fig_fname)

In [ ]:
import globvars as gv

In [ ]:
import os
s = '_S01_parcel_aal_grp10-0_allb_beta_ML_nr4_7chs_nfeats384_pcadim161_skip32_wsz256__(merge_nothing,basic).npz'  
f = np.load(os.path.join(gv.data_dir, s),allow_pickle=True )

In [ ]:
import utils_postprocess as pp
#pp.total_size(f)

In [ ]:
list( f.keys() )

In [ ]:
results_cur = f['results_cur'][()]

In [ ]:
results_cur['perfs_XGB'][0].keys()

In [ ]:
    #res_cur = f['results_cur'][()]
#     for lda_anver in res_cur['lda_analysis_versions'].values():
#         keys_to_clean = ['X_transformed', 'ldaobj', 'ldaobjs']
#         for subver in lda_anver.values():
#             for ktc in keys_to_clean:
#                 if ktc in subver:
#                     print('delted ',ktc)
#                     #del subver[ktc]
#         #del lda_anver['ldaobj']
#     if 'Xconcat_good_cur' in res_cur:
#         print('delted Xconcat_good_cur')
#         #del res_cur['Xconcat_good_cur']
    #del res_cur['transformed_imputed']
    #del res_cur['transformed_imputed_CV']
    for pt in ['perfs_XGB','perfs_XGB_fs' ]:
        for i in range(len(res_cur[pt]) ):
            if 'clf_obj' in res_cur[pt][i]:
                print('delted clf_obj')
                #del res_cur[pt]['clf_obj']

In [ ]:
pp.total_size(results_cur, minRepSz=None)

In [ ]:
list(res_cur.keys())

In [ ]:


res_cleaned = removeLargeItems(res_cur)
pp.total_size(res_cleaned, minRepSz=None)

In [ ]:
import gc;gc.collect()
pp.total_size(res_cleaned, minRepSz=None)

In [ ]:
import importlib as il
il.reload(pp)

In [ ]:
pp.total_size(results_cur, minRepSz=None), pp.total_size(res_cleaned, minRepSz=None)

In [ ]:
457378611 / 456345583

In [ ]:
results_cur.keys()

In [ ]:
pp.total_size(f)

In [ ]:
res_cleaned

In [ ]:
for kk,item in res_cleaned['featsel_per_method'].items():
    print(pp.total_size(item,minRepSz=None), kk)

In [ ]:
for kk,item in res_cleaned['featsel_per_method']['XGB_Shapley'].items():
    print(pp.total_size(item,minRepSz=None), kk)

In [ ]:
for kk,item in res_cleaned['featsel_per_method']['interpret_EBM']['info_per_cp'][('trem_L', 'notrem_L')]['explainer'].__dict__.items():
    print(pp.total_size(item,minRepSz=None), kk)

In [ ]:
for kk,item in res_cleaned.items():
    print(pp.total_size(item,minRepSz=None), kk)

In [ ]:
#lda_output_pg_cur
#for kk,item in lda_output_pg_cur['merge_movements']['basic'].items():
for kk,item in res_cleaned['lda_analysis_versions']['all_present_features']['fit_to_all_data'].items():
    print(pp.total_size(item, verbose=0), kk  )

In [ ]:
x_for_heavy

In [ ]:
len(class_labels_good_for_classif)

In [ ]:
X_for_heavy.shape

In [ ]:
np.savez('tst16.npz',X_for_heavy=X_for_heavy,class_labels_good_for_classif=class_labels_good_for_classif,
       add_fitopts=add_fitopts, clf_XGB= clf_XGB )

In [ ]:
# np.savez('tst.npz',X_for_heavy=X_for_heavy,class_labels_good_for_classif=class_labels_good_for_classif,
#        add_fitopts=add_fitopts, clf_XGB= clf_XGB )

In [ ]:
X.shape

In [ ]:
import numpy as np
f = np.load('tst16.npz',allow_pickle=True)
X_for_heavy = f['X_for_heavy']
class_labels_good_for_classif = f['class_labels_good_for_classif']
#clf_XGB = f['clf_XGB'][()]
add_fitopts = f['add_fitopts'][()]

X = X_for_heavy
y = class_labels_good_for_classif
##
#X = np.random.uniform(size=X_for_heavy.shape)
# X = np.random.uniform(size=(300,10))
# y = class_labels_good_for_classif[:300]

add_fitopts['eval_metric'] = 'mlogloss'

from xgboost import XGBClassifier


add_clf_creopts={ 'n_jobs':128, 'use_label_encoder':False,
                 'importance_type': 'total_gain' }
tree_method = 'exact'
method_params = {'tree_method': tree_method}

add_clf_creopts.update(method_params)
clf_XGB = XGBClassifier(**add_clf_creopts)

print(X_for_heavy.shape,class_labels_good_for_classif.shape)
display(clf_XGB)

clf_XGB.fit(X, y, **add_fitopts)

In [ ]:
clf_XGB.fit(X_for_heavy, class_labels_good_for_classif, **add_fitopts)

In [ ]:
clf_XGB

In [ ]:
add_fitopts

In [ ]:
getrusage()

In [ ]:
help(psutil.virtual_memory())

In [ ]:
GB = 1024**3

In [ ]:
import psutil
psutil.virtual_memory().free / GB

In [ ]:
psutil.virtual_memory().total / GB

In [ ]:
!free -g

In [ ]:
fbands_per_mod.keys()

In [ ]:
opts

In [ ]:
#      A 1-D or 2-D array containing multiple variables and observations.
#         Each row of `x` represents a variable, and each column a single
#         observation of all those variables. Also see `rowvar` below.

In [ ]:
from featlist import parseFeatNames
parseFeatNames(featnames,n_jobs=1)

In [ ]:
featnames[500:550]

In [ ]:
hist, bin_edges = np.histogram(C_nocenter.flatten(), bins=20, density=False)

In [ ]:
np.max(C_nocenter)

In [ ]:
np.max(bin_edges)

In [ ]:
ax = plt.gca()
ax.bar(bin_edges[:-1],hist)
ax.set_xlim(np.min(bin_edges),np.max(bin_edges))

In [ ]:
nr = 1; nc = 2;
ww = 5; hh = 4
fig,axs = plt.subplots(nr,nc, figsize=(nc*ww, nr*hh))
ax = axs[0]
ax.hist(C_nocenter.flatten());
ax = axs[1]
#ax.pcolor(C_nocenter)

In [ ]:
#maxind = np.argmax(C_nocenter)
C_flat = C_nocenter.flatten()
sinds = np.argsort(C_flat)
for i in sinds[-100:][::-1]:
    coords = np.unravel_index(i, C_nocenter.shape)
    if coords[0] < coords[1]:
        continue
    print( f'{C_nocenter[coords]:.3f} {featnames[coords[0]]} <-> {featnames[coords[1]]}' )

In [ ]:
strong_correl = np.where( C_flat > 0.5 )


In [ ]:
np.sum( C_flat > 0.5 )//2 , len(C_flat)//2, np.sum( C_flat > 0.5 ) / len(C_flat)

In [ ]:
A = np.random.choice(feature_names_all,3)
o = parseFeatNames(A,n_jobs=1)
display('test_input=',A)
display('test_output=',o)

In [ ]:
parsed_featnames = parseFeatNames(feature_names_all)

In [ ]:
np.ones(5,dtype=bool) & np.zeros(5,dtype=bool)

In [ ]:
np.array(['fsd', 'fds']  ) == 'as'

In [ ]:
parsed_featnames.keys()

In [ ]:
sum(r)

In [ ]:
inds = np.where( np.array(parsed_featnames['mod2'] ) != 'LFP' )[0]
print(len(inds))
feature_names_all[inds]

In [ ]:
feature_names_all[inds][800:]

In [ ]:
inds = np.where( np.array(parsed_featnames['mod1'] ) != 'msrc' )[0]
print(len(inds))
feature_names_all[inds]

In [ ]:
r = np.logical_and(np.array(parsed_featnames['fb1'] ) == 'beta' , \
 np.logical_or( np.array(parsed_featnames['fb2'] ) == 'gamma' , 
               (np.array(parsed_featnames['fb2'] ) == 'tremor' ) ) )
#r = np.logical_and(  np.array(parsed_featnames['mod1'] ) == 'mscr', r )
#r = np.logical_and(  np.array(parsed_featnames['mod2'] ) == 'LFP', r )

sum(r)

In [ ]:
data_modalities

In [ ]:
fbands_per_mod

In [ ]:
from featlist import getBadInds_doubleBandFeats 
#%debug
bf = getBadInds_doubleBandFeats(feature_names_all, data_modalities,
                               fbands_per_mod, fbands_def, printLog=0,
                               parsed_featnames=parsed_featnames)


In [ ]:
bf

In [ ]:
feature_names_all[np.setdiff1d( np.arange(len(feature_names_all) ), bf ) ]

In [ ]:
feature_names_all[2:200]

In [ ]:
re.compile('^.*_(\w+)_.*' ).match('fsdafd_555dsfs_fdsfds_&$#*_fdsfffffgfggg_').groups()

In [ ]:
parsed_featnames['fb1'][2:200]

In [ ]:
feature_names_all[0]

In [ ]:
parsed_featnames[0]

In [ ]:
data_modalities

In [ ]:
featnames

In [ ]:
from featlist import parseFeatNames
r = parseFeatNames(featnames)

In [ ]:
r['mod1']

In [ ]:
featnames

In [ ]:
len(featnames_nice)

In [ ]:
parcel_group_names

In [ ]:
roi_labels.keys(), parcel_types

In [ ]:
revdict

In [ ]:
featsel_per_method['interpret_EBM']['info_per_cp'].keys()

In [ ]:
explainer_cur = featsel_per_method['interpret_EBM']['info_per_cp'][('trem_L', 'notrem_L')]['explainer']

In [ ]:
interpret.show(explainer_cur)

In [ ]:
featsel_per_method = results_cur['featsel_per_method'] 
fsh = 'XGB_total_gain'
info = featsel_per_method[fsh]
scores_XGB_total_gain = info['scores']

fsh = 'XGB_Shapley'
info = featsel_per_method[fsh]
shapley_values = info['scores']  # dim = 3

In [ ]:
featsel_per_method.keys()

In [ ]:
scores.shape

In [ ]:
revdict

In [ ]:
for lblind in range(shap_values.shape[1] ):
    plt.figure(figsize = (20,5))
    ax = plt.gca()
    utsne.plotFeatureImportance(ax, featnames_nice, shapley_values[:,lblind,:20], 'XGB_Shapley')
    ax.set_title( ax.get_title() + f'_lblind={lblind}' )

In [ ]:
shap_values

In [ ]:
fsh

In [ ]:
do_XGB_cur

## Inspect explainable AI

In [ ]:
# results_cur['featsel_importances_res'] = featsel_importances_res
# results_cur['featsel_explainer_res'] = featsel_importances_res


In [ ]:
results_cur['featsel_per_method'].keys()

In [ ]:

#for fsh,info in featsel_per_method.items():
    

In [ ]:
info.keys()

In [ ]:
featsel_explainers_res.keys()

In [ ]:
#featsel_explainers_res['interpret_EBM']

In [ ]:
interpret.show(explainer)

In [ ]:
from sklearn.metrics import confusion_matrix
preds = ebm.predict(X)
# Confusion matrix whose i-th row and j-th column entry indicates the number
# of samples with true label being i-th class and predicted label being j-th
# class.   confmat[i,j] -- true i'th predicted being j'th
confmat = confusion_matrix(preds, y)


In [ ]:
confmat